"""add selected to quiz_answers

Revision ID: edd66cbb6bb1
Revises: 5c590b81f167
Create Date: 2025-12-19 11:19:52.305228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edd66cbb6bb1'
down_revision = '5c590b81f167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected', sa.Text(), nullable=False))
        batch_op.drop_constraint(batch_op.f('quiz_answers_attempt_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'quiz_attempts', ['attempt_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('quiz_attempts_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('quiz_attempts_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('quiz_answers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('quiz_answers_attempt_id_fkey'), 'quiz_attempts', ['attempt_id'], ['id'])
        batch_op.drop_column('selected')

    # ### end Alembic commands ###
